### ISSUE TITLE
Two feature requests (one may be a bug?)

### ISSUE THREAD

**Issue by designosis** [ssddanbrown/HtmlDiff#3]
This is really excellent, thank you for making it public! A few observations:

1) The option to specify – or entirely omit – the class name would be useful. `<del>blah</del>` is more efficient, and I can still use a containing element for CSS (e.g. `div.mydiff del { text-decoration:none;color:#f00}`).

2) Newlines between elements (such as `<p>Blah</p>\n\n<p>Blah2</p>\n\n<p>Blah3</p>` add empty `<del class="diffdel"></del>` elements between each paragraph. The setting `$diff->ignoreWhitespaceDifferences = true` doesn't change this.

Thanks again!

**Comment by ssddanbrown** [comment]
Hi @neokio, Thanks for the feedback.

1. The class provides some additional context upon the tag alone, primarily to indicate areas of modification upon just additions/deletions. If it really is valuable to change/omit these classes I'd be happy for a PR to be made to allow settings of these, including to empty values to omit classes. Ideally would want some tests with that PR.
2. From my testing of this scenario, the `<del>` in the output accurately contains the removed newlines. Newlines between elements are not ignored since they can be considered part of content. The `ignoreWhitespaceDifferences` controls whether or not all whitespace are considered to be equal, not full ignoring of whitespace. I'd suggest maybe cleaning input HTML if this is desired, or parsing diff output to remove whitespace-only-diffs. Building this into the library would add complexity, especially as we attempt to identity important whitespace which can be ambiguous.

**Comment by designosis** [comment]
1) I'll make a PR this week :)

2) This was my error! I thought both compared strings were identical, but the tinymce editor was removing all `\n\n` from the second string.

**Comment by ssddanbrown** [comment]
Awesome! I'll therefore close this off. Feel free to still comment here or via your PR if you need further assistance.
